Decidim 0.28.2
Platoniq/decidim-inspire pull request #7
Opened 2024-07-18 12:59 UTC by HHassig

This is a skip of 0.28.1 so the one-time actions were:

- bin/rails decidim:upgrade:fix_orphan_categorizations
- (didn't affect anything)

- [3.1. Verifications documents configurations](https://github.com/decidim/decidim/releases/tag/v0.28.1)
- We have not done this previously

2024-07-18 13:04 UTC, fblupi requested changes

2024-07-18 13:04 UTC, fblupi commented on package.json
>      "@decidim/dev": "^0.28.0",
You should change the version for these packages too.

2024-07-22 11:49 UTC, HHassig commented
@fblupi Works as expected.

2024-07-22 11:53 UTC, fblupi approved these changes

2024-07-22 11:53 UTC, merged